project:
  type: website

website:
  title: "If√° for Beginners"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: orisha.qmd
        text: Orisha
      - href: dictionary.qmd
        text: Dictionary

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

execute: 
  freeze: auto